// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/shardpb/shard.proto

package shardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headline      string                 `protobuf:"bytes,3,opt,name=headline,proto3" json:"headline,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Vector        []float32              `protobuf:"fixed32,6,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	ShardId       int32                  `protobuf:"varint,7,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_internal_shardpb_shard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shardpb_shard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_internal_shardpb_shard_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Article) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

func (x *Article) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *Article) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *Article) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_internal_shardpb_shard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shardpb_shard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_internal_shardpb_shard_proto_rawDescGZIP(), []int{1}
}

func (x *SearchHit) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *SearchHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_internal_shardpb_shard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shardpb_shard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_internal_shardpb_shard_proto_rawDescGZIP(), []int{2}
}

func (x *InsertRequest) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_internal_shardpb_shard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shardpb_shard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_internal_shardpb_shard_proto_rawDescGZIP(), []int{3}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_internal_shardpb_shard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shardpb_shard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_internal_shardpb_shard_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_internal_shardpb_shard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shardpb_shard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_internal_shardpb_shard_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_internal_shardpb_shard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shardpb_shard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_shardpb_shard_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_internal_shardpb_shard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shardpb_shard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_internal_shardpb_shard_proto_rawDescGZIP(), []int{7}
}

type SearchSimilarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         []float32              `protobuf:"fixed32,1,rep,packed,name=query,proto3" json:"query,omitempty"`
	K             int32                  `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSimilarRequest) Reset() {
	*x = SearchSimilarRequest{}
	mi := &file_internal_shardpb_shard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSimilarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSimilarRequest) ProtoMessage() {}

func (x *SearchSimilarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shardpb_shard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSimilarRequest.ProtoReflect.Descriptor instead.
func (*SearchSimilarRequest) Descriptor() ([]byte, []int) {
	return file_internal_shardpb_shard_proto_rawDescGZIP(), []int{8}
}

func (x *SearchSimilarRequest) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchSimilarRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

type SearchSimilarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchHit           `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSimilarResponse) Reset() {
	*x = SearchSimilarResponse{}
	mi := &file_internal_shardpb_shard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSimilarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSimilarResponse) ProtoMessage() {}

func (x *SearchSimilarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shardpb_shard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSimilarResponse.ProtoReflect.Descriptor instead.
func (*SearchSimilarResponse) Descriptor() ([]byte, []int) {
	return file_internal_shardpb_shard_proto_rawDescGZIP(), []int{9}
}

func (x *SearchSimilarResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

type ListArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_internal_shardpb_shard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shardpb_shard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_internal_shardpb_shard_proto_rawDescGZIP(), []int{10}
}

type ListArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesResponse) Reset() {
	*x = ListArticlesResponse{}
	mi := &file_internal_shardpb_shard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResponse) ProtoMessage() {}

func (x *ListArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shardpb_shard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return file_internal_shardpb_shard_proto_rawDescGZIP(), []int{11}
}

func (x *ListArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

var File_internal_shardpb_shard_proto protoreflect.FileDescriptor

const file_internal_shardpb_shard_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/shardpb/shard.proto\x12\x12articledb.shard.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x01\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\bheadline\x18\x03 \x01(\tR\bheadline\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06vector\x18\x06 \x03(\x02R\x06vector\x12\x19\n" +
	"\bshard_id\x18\a \x01(\x05R\ashardId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"X\n" +
	"\tSearchHit\x125\n" +
	"\aarticle\x18\x01 \x01(\v2\x1b.articledb.shard.v1.ArticleR\aarticle\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"F\n" +
	"\rInsertRequest\x125\n" +
	"\aarticle\x18\x01 \x01(\v2\x1b.articledb.shard.v1.ArticleR\aarticle\"\x10\n" +
	"\x0eInsertResponse\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\vGetResponse\x125\n" +
	"\aarticle\x18\x01 \x01(\v2\x1b.articledb.shard.v1.ArticleR\aarticle\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eDeleteResponse\":\n" +
	"\x14SearchSimilarRequest\x12\x14\n" +
	"\x05query\x18\x01 \x03(\x02R\x05query\x12\f\n" +
	"\x01k\x18\x02 \x01(\x05R\x01k\"J\n" +
	"\x15SearchSimilarResponse\x121\n" +
	"\x04hits\x18\x01 \x03(\v2\x1d.articledb.shard.v1.SearchHitR\x04hits\"\x15\n" +
	"\x13ListArticlesRequest\"O\n" +
	"\x14ListArticlesResponse\x127\n" +
	"\barticles\x18\x01 \x03(\v2\x1b.articledb.shard.v1.ArticleR\barticles2\xc1\x03\n" +
	"\fShardService\x12O\n" +
	"\x06Insert\x12!.articledb.shard.v1.InsertRequest\x1a\".articledb.shard.v1.InsertResponse\x12F\n" +
	"\x03Get\x12\x1e.articledb.shard.v1.GetRequest\x1a\x1f.articledb.shard.v1.GetResponse\x12O\n" +
	"\x06Delete\x12!.articledb.shard.v1.DeleteRequest\x1a\".articledb.shard.v1.DeleteResponse\x12d\n" +
	"\rSearchSimilar\x12(.articledb.shard.v1.SearchSimilarRequest\x1a).articledb.shard.v1.SearchSimilarResponse\x12a\n" +
	"\fListArticles\x12'.articledb.shard.v1.ListArticlesRequest\x1a(.articledb.shard.v1.ListArticlesResponseB:Z8github.com/davisclrk/article_db/internal/shardpb;shardpbb\x06proto3"

var (
	file_internal_shardpb_shard_proto_rawDescOnce sync.Once
	file_internal_shardpb_shard_proto_rawDescData []byte
)

func file_internal_shardpb_shard_proto_rawDescGZIP() []byte {
	file_internal_shardpb_shard_proto_rawDescOnce.Do(func() {
		file_internal_shardpb_shard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_shardpb_shard_proto_rawDesc), len(file_internal_shardpb_shard_proto_rawDesc)))
	})
	return file_internal_shardpb_shard_proto_rawDescData
}

var file_internal_shardpb_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_shardpb_shard_proto_goTypes = []any{
	(*Article)(nil),               // 0: articledb.shard.v1.Article
	(*SearchHit)(nil),             // 1: articledb.shard.v1.SearchHit
	(*InsertRequest)(nil),         // 2: articledb.shard.v1.InsertRequest
	(*InsertResponse)(nil),        // 3: articledb.shard.v1.InsertResponse
	(*GetRequest)(nil),            // 4: articledb.shard.v1.GetRequest
	(*GetResponse)(nil),           // 5: articledb.shard.v1.GetResponse
	(*DeleteRequest)(nil),         // 6: articledb.shard.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 7: articledb.shard.v1.DeleteResponse
	(*SearchSimilarRequest)(nil),  // 8: articledb.shard.v1.SearchSimilarRequest
	(*SearchSimilarResponse)(nil), // 9: articledb.shard.v1.SearchSimilarResponse
	(*ListArticlesRequest)(nil),   // 10: articledb.shard.v1.ListArticlesRequest
	(*ListArticlesResponse)(nil),  // 11: articledb.shard.v1.ListArticlesResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_internal_shardpb_shard_proto_depIdxs = []int32{
	12, // 0: articledb.shard.v1.Article.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: articledb.shard.v1.SearchHit.article:type_name -> articledb.shard.v1.Article
	0,  // 2: articledb.shard.v1.InsertRequest.article:type_name -> articledb.shard.v1.Article
	0,  // 3: articledb.shard.v1.GetResponse.article:type_name -> articledb.shard.v1.Article
	1,  // 4: articledb.shard.v1.SearchSimilarResponse.hits:type_name -> articledb.shard.v1.SearchHit
	0,  // 5: articledb.shard.v1.ListArticlesResponse.articles:type_name -> articledb.shard.v1.Article
	2,  // 6: articledb.shard.v1.ShardService.Insert:input_type -> articledb.shard.v1.InsertRequest
	4,  // 7: articledb.shard.v1.ShardService.Get:input_type -> articledb.shard.v1.GetRequest
	6,  // 8: articledb.shard.v1.ShardService.Delete:input_type -> articledb.shard.v1.DeleteRequest
	8,  // 9: articledb.shard.v1.ShardService.SearchSimilar:input_type -> articledb.shard.v1.SearchSimilarRequest
	10, // 10: articledb.shard.v1.ShardService.ListArticles:input_type -> articledb.shard.v1.ListArticlesRequest
	3,  // 11: articledb.shard.v1.ShardService.Insert:output_type -> articledb.shard.v1.InsertResponse
	5,  // 12: articledb.shard.v1.ShardService.Get:output_type -> articledb.shard.v1.GetResponse
	7,  // 13: articledb.shard.v1.ShardService.Delete:output_type -> articledb.shard.v1.DeleteResponse
	9,  // 14: articledb.shard.v1.ShardService.SearchSimilar:output_type -> articledb.shard.v1.SearchSimilarResponse
	11, // 15: articledb.shard.v1.ShardService.ListArticles:output_type -> articledb.shard.v1.ListArticlesResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_shardpb_shard_proto_init() }
func file_internal_shardpb_shard_proto_init() {
	if File_internal_shardpb_shard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_shardpb_shard_proto_rawDesc), len(file_internal_shardpb_shard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_shardpb_shard_proto_goTypes,
		DependencyIndexes: file_internal_shardpb_shard_proto_depIdxs,
		MessageInfos:      file_internal_shardpb_shard_proto_msgTypes,
	}.Build()
	File_internal_shardpb_shard_proto = out.File
	file_internal_shardpb_shard_proto_goTypes = nil
	file_internal_shardpb_shard_proto_depIdxs = nil
}
